# Generated by Django 3.2.9 on 2021-11-14 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scraper", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="scraperresponse",
            old_name="has_request_failed",
            new_name="failed_request",
        ),
    ]
